export { default as App } from "./App";
export { default as Login } from "./users/Login";
export { default as Logout } from "./users/Logout";
export { default as Register } from "./users/Register";
// export { default as AddToCart } from "./AddToCart";
// export { default as Cart } from "./Cart";
// export { default as Care } from "./Care";
// export { default as Confirmation } from "./Confirmation";
// export { default as DeleteFromCart } from "./DeleteFromCart";
// export { default as EditCart } from "./EditCart";
// export { default as Account } from "./Account";
export { default as Home } from "./Home";
export { default as Header } from "./Header";
// export { default as RenderAllPlants } from "./RenderAllPlants";
// export { default as RenderDivas } from "./RenderDivas";
// export { default as RenderGreenThumbs } from "./RenderGreenThumbs";
// export { default as RenderPlantNoobs } from "./RenderPlantNoobs";
// export { default as RenderPots } from "./RenderPots";
// export { default as SingleProducts } from "./SingleProducts";